version: '3.8'

services:

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://sqlserver:1433;databaseName=master;trustServerCertificate=true;encrypt=false;
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092